INSERT INTO TESTCHILD (ID, CHILDID, DESCRIPTION)
VALUES
(1, 1, 'Child description 1.1');

INSERT INTO TESTCHILD (ID, CHILDID, DESCRIPTION)
VALUES
(1, 2, 'Child description 1.1');

INSERT INTO TESTCHILD (ID, CHILDID, DESCRIPTION)
VALUES
(2, 1, 'Child description 2.1');

INSERT INTO TESTCHILD (ID, CHILDID, DESCRIPTION)
VALUES
(2, 2, 'Child description 2.2');
