CREATE TABLE TEST_WITH_ARRAY
(
	ID INT64 NOT NULL,
	ID2 ARRAY<INT64>,
	UUID ARRAY<BYTES(16)> NOT NULL,
	ACTIVE ARRAY<BOOL>,
	AMOUNT ARRAY<FLOAT64>,
	DESCRIPTION ARRAY<STRING(100)>,
	CREATED_DATE ARRAY<DATE>,
	LAST_UPDATED ARRAY<TIMESTAMP>
) PRIMARY KEY (ID)
