CREATE TABLE TEST_WITH_ARRAY
(
	ID INT64 NOT NULL,
	UUID BYTES(16) NOT NULL,
	ACTIVE BOOL,
	AMOUNT FLOAT64,
	DESCRIPTION STRING(100),
	CREATED_DATE DATE,
	LAST_UPDATED TIMESTAMP,
	OTHER_DESCRIPTIONS ARRAY<STRING(100)>
) PRIMARY KEY (ID)
