CREATE TABLE IF NOT EXISTS TEST
(
	ID INT64 NOT NULL,
	UUID BYTES(16) NOT NULL,
	ACTIVE BOOL,
	AMOUNT FLOAT64,
	DESCRIPTION STRING(100),
	CREATED_DATE DATE,
	LAST_UPDATED TIMESTAMP
) PRIMARY KEY (ID)
