SET_CONNECTION_PROPERTY AsyncDdlOperations=true;

CREATE TABLE ASYNCTEST
(
	ID INT64 NOT NULL,
	UUID BYTES(16) NOT NULL,
	ACTIVE BOOL,
	AMOUNT FLOAT64,
	DESCRIPTION STRING(100),
	CREATED_DATE DATE,
	LAST_UPDATED TIMESTAMP
) PRIMARY KEY (ID)
;

WAIT_FOR_DDL_OPERATIONS;
RESET_CONNECTION_PROPERTY AsyncDdlOperations;
